### ISSUE TITLE
Pantalla gris

### ISSUE THREAD

**Issue by jsga** [alazaro/game_of_life#1]
Instalando los requirements, y haciendo `python src/game.py` me sale una pantalla gris...

![image](https://user-images.githubusercontent.com/18591197/79442625-1975c200-7fd9-11ea-8a76-9df7c66428cb.png)

**Comment by alazaro** [comment]
Prueba a actualizar y volver a instalar requirements. He cambiado la versión de PyGame.

**Comment by jsga** [comment]
Works :)
![image](https://user-images.githubusercontent.com/18591197/79579297-aeef7f80-80c7-11ea-800a-b26888ca122c.png)
